version: "3.7"

services:
  client:
    restart: unless-stopped
    build:
      context: ./client
    ports:
      - 3000:3000

  server:
    restart: unless-stopped
    build:
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 4000:4000

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./client/build:/usr/share/nginx/html

  certbot:
    build:
      context: ./deploy/certbot
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
      - ./deploy/nginx:/etc/nginx
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
