version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3001"
    networks:
      - gbb-net

  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4000:4000"
    networks:
      - gbb-net

# probably don't need to specify the network
networks:
  gbb-net:
