version: "3.7"

services:
  client:
    restart: unless-stopped
    build:
      context: ./server # Adjust the path to point to your server directory
      dockerfile: ../deploy/server/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./deploy/nginx:/etc/nginx/conf.d
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  server:
    restart: unless-stopped
    build:
      context: ./server # Adjust the path to point to your server directory
      dockerfile: ../deploy/server/Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 4000:4000
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./deploy/certbot/conf:/etc/letsencrypt
      - ./deploy/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
